set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE
    "${CMAKE_CURRENT_LIST_DIR}/../cmake/toolchains/mingw-w64-x86_64.cmake")

string(APPEND VCPKG_C_FLAGS " -D____FIReference_1_boolean_INTERFACE_DEFINED__")
string(APPEND VCPKG_CXX_FLAGS " -std=c++23 -D____FIReference_1_boolean_INTERFACE_DEFINED__")
