//
// Copyright (C) 2026 PHTNC<>.
// Licensed under GPLv3.0 with Plugin Interface exceptions.
//
#pragma once

#include <filesystem>
#include <functional>
#include <optional>
#include <sdk/api.h>
#include <sdk/statuscode.h>
#include <vertex/log/ilog.hh>
#include <vertex/runtime/function_registry.hh>

#include "plugin_move_semantics.hh"
#include "plugin_functions.hh"

namespace Vertex::Runtime
{
    class Plugin final
    {
      public:
        explicit Plugin(Log::ILog& logService) noexcept : m_logService(logService) {}
        ~Plugin();

        void set_path(const std::filesystem::path& path) noexcept
        {
            m_path = path;
        }

        [[nodiscard]] const std::filesystem::path& get_path() const noexcept
        {
            return m_path;
        }

        [[nodiscard]] std::string get_filename() const noexcept
        {
            return m_path.filename().string();
        }

        [[nodiscard]] const PluginInformation& get_plugin_info() const noexcept
        {
            return m_pluginInfo;
        }

        [[nodiscard]] PluginInformation& get_plugin_info() noexcept
        {
            return m_pluginInfo;
        }

        void set_library(Library&& library) noexcept
        {
            m_library = std::move(library);
        }

        [[nodiscard]] Library& get_library() noexcept
        {
            return *m_library;
        }

        [[nodiscard]] const Library& get_library() const noexcept
        {
            return *m_library;
        }

        [[nodiscard]] bool operator==(const Plugin& other) const noexcept
        {
            return m_path == other.m_path;
        }

        [[nodiscard]] bool operator!=(const Plugin& other) const noexcept
        {
            return !(*this == other);
        }

        Plugin(const Plugin&) = delete;
        Plugin& operator=(const Plugin&) = delete;

        Plugin(Plugin&& other) noexcept
            : m_pluginInfo(other.m_pluginInfo),
              m_path(std::move(other.m_path)),
              m_library(std::move(other.m_library)),
              m_logService(other.m_logService),
              VERTEX_PLUGIN_MOVE_INIT_LIST // Auto-generated by the build system
        {
            VERTEX_PLUGIN_MOVE_NULLIFY // Auto-generated by the build system
        }

        Plugin& operator=(Plugin&& other) noexcept
        {
            if (this != &other)
            {
                m_pluginInfo = other.m_pluginInfo;
                m_path = std::move(other.m_path);
                m_library = std::move(other.m_library);
                m_logService = other.m_logService;

                VERTEX_PLUGIN_MOVE_ASSIGN_COPY // Auto-generated by the build system

                VERTEX_PLUGIN_MOVE_ASSIGN_NULLIFY // Auto-generated by the build system
            }
            return *this;
        }

      private:
        void reset_function_pointers() noexcept
        {
            auto& other = *this;
            VERTEX_PLUGIN_MOVE_NULLIFY
        }

        PluginInformation m_pluginInfo{};
        std::filesystem::path m_path{};
        std::optional<Library> m_library{};
        std::reference_wrapper<Log::ILog> m_logService;

      public:
        VertexRuntime m_runtime{};

        VERTEX_PLUGIN_FUNCTION_POINTERS // Auto-generated by the build system

        void unload();

        [[nodiscard]] bool is_loaded() const noexcept
        {
            return m_library.has_value();
        }

        [[nodiscard]] bool has_feature(const uint64_t feature) const noexcept
        {
            return (m_pluginInfo.featureCapability & feature) != 0;
        }
    };
}
